% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Jun-2025 08:56:47
%  MATLAB version: 9.13.0.2049777 (R2022b)
% -------------------------------------------------------------------
saveVarsMat = load('plotting_f7_ST_NOFPU.mat');

ETS_param = saveVarsMat.ETS_param; % <11x3000 double> too many elements

NLLS_param = saveVarsMat.NLLS_param; % <11x3000 double> too many elements

dados = [0.82844283031874; 1.02827455448763; 0.966929731242057; 0.0635908945801672; ...
         0.185157258814921; -0.133757056527947; 0.0198866882667842; -0.0436973720156655; ...
         0.0217898663482543];

i = 3000;

j = 9;

strg_save = 'param_3000.csv';
strg_save = convertCharsToStrings(strg_save);

clear saveVarsMat;
